Add support for PostgreSQL 16
eeshugerman/postgres-backup-s3 pull request #39
Opened 2023-09-24 18:21 UTC by ledermann

2023-09-28 14:24 UTC, IgorZvezdilin commented
Hi guys! I believe that you approve this commit!

2023-10-16 06:32 UTC, mederic-p commented
Hey, can we merge this?

2023-10-16 10:58 UTC, kije commented
Also eagerly awaiting this :)

2023-10-19 03:44 UTC, eeshugerman commented
Thanks @ledermann for the PR! Has anyone tested this out? Best I can tell Postgres v16 is not available in Alpine v3.18.

2023-10-19 08:06 UTC, ledermann commented
@eeshugerman Yes, it seems this PR is a bit premature - support for PostgreSQL 16 has not landed in Alpine 3.18:

```bash
$ docker run -it --rm alpine /bin/sh

/ # apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/aarch64/APKINDEX.tar.gz
v3.18.4-82-gbad06ca2153 [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
v3.18.4-80-g1df2bca78e9 [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
OK: 19946 distinct packages available

/ # apk add postgresql-client
(1/8) Installing postgresql-common (1.2-r0)
Executing postgresql-common-1.2-r0.pre-install
(2/8) Installing lz4-libs (1.9.4-r4)
(3/8) Installing libpq (15.4-r0)
(4/8) Installing ncurses-terminfo-base (6.4_p20230506-r0)
(5/8) Installing libncursesw (6.4_p20230506-r0)
(6/8) Installing readline (8.2.1-r1)
(7/8) Installing zstd-libs (1.5.5-r4)
(8/8) Installing postgresql15-client (15.4-r0)
Executing busybox-1.36.1-r2.trigger
Executing postgresql-common-1.2-r0.trigger
* Setting postgresql15 as the default version
OK: 13 MiB in 23 packages

/ # apk add postgresql16-client
ERROR: unable to select packages:
  postgresql16-client (no such package):
    required by: world[postgresql16-client]
```

Currently, `postgresql16-client` is available in Edge only:
https://pkgs.alpinelinux.org/packages?name=postgresql16-client&branch=edge&repo=&arch=&maintainer=

I guess we'll have to wait a little longer.

2023-12-12 14:14 UTC, eeshugerman commented
Any volunteers to test this?

2023-12-16 15:26 UTC, Ardakilic commented
@eeshugerman I can try if that would help. I can try if a test version is tagged. I make a daily backup on a database on my docker compose and since v16 it has been stopped.

2023-12-17 22:39 UTC, eeshugerman commented
Thanks @Ardakilic; I found some free time so went ahead and tested myself.

There is a minor snag:
```
#7 5.888 + pip3 install awscli
#7 7.026 error: externally-managed-environment
#7 7.026 
#7 7.026 × This environment is externally managed
#7 7.026 ╰─> 
#7 7.026     The system-wide python installation should be maintained using the system
#7 7.026     package manager (apk) only.
#7 7.026     
#7 7.026     If the package in question is not packaged already (and hence installable via
#7 7.026     "apk add py3-somepackage"), please consider installing it inside a virtual
#7 7.026     environment, e.g.:
#7 7.026     
#7 7.026     python3 -m venv /path/to/venv
#7 7.026     . /path/to/venv/bin/activate
#7 7.026     pip install mypackage
#7 7.026     
#7 7.026     To exit the virtual environment, run:
#7 7.026     
#7 7.026     deactivate
#7 7.026     
#7 7.026     The virtual environment is not deleted, and can be re-entered by re-sourcing
#7 7.026     the activate file.
#7 7.026     
#7 7.026     To automatically manage virtual environments, consider using pipx (from the
#7 7.026     pipx package).
#7 7.026 
#7 7.026 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
#7 7.026 hint: See PEP 668 for the detailed specification.
#7 ERROR: process "/bin/sh -c sh install.sh && rm install.sh" did not complete successfully: exit code: 1
```

We can address this by switching from `pip3 install awscli` to `apk add aws-cli` in `install.sh`. This doesn't work on Alpine v3.10, which we use for Postgres v11, but that's fine -- we can drop Postgres v11 support.

2023-12-17 23:23 UTC, Ardakilic commented
Since Postgres 11 users can still use the old tag, and [its final release is due date already](https://www.postgresql.org/support/versioning/), I'd personally go for it.

2023-12-19 14:33 UTC, eeshugerman requested changes
The build fails -- see https://github.com/eeshugerman/postgres-backup-s3/pull/39#issuecomment-1859308291

2023-12-20 09:32 UTC, Ardakilic commented
I believe this line should be removed:

https://github.com/eeshugerman/postgres-backup-s3/pull/39/files#diff-aa526adb0a3d690b8bce5b9ae75da3c3a254ebeffe4b108851b60d8746356276R14

And these two lines should be modified as @eeshugerman mentioned:

https://github.com/eeshugerman/postgres-backup-s3/blob/aca41c2af4a3633557af29a2a5d2a988f6211972/src/install.sh#L15-L16C19

@ledermann could you check please?

2023-12-20 09:59 UTC, ledermann commented
Sorry, folks, for not testing my own PR. I have made the changes as requested. Now, the Docker image builds fine for Alpine from `3.12` to `3.19`.

2023-12-21 21:45 UTC, eeshugerman approved these changes

2023-12-21 21:46 UTC, eeshugerman commented
Looks good, thanks @ledermann!

2023-12-21 21:47 UTC, merged